export const ErrorCode = {
  BAD_REQUEST: "BAD_REQUEST",
  UNAUTHENTICATED: "UNAUTHENTICATED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  RATE_LIMITED: "RATE_LIMITED",
  DATABASE_ERROR: "DATABASE_ERROR",
  INTERNAL_ERROR: "INTERNAL_ERROR",

  // Inventory: product groups
  PRODUCT_GROUP_NOT_FOUND: "PRODUCT_GROUP_NOT_FOUND",
  DUPLICATE_PRODUCT_GROUP: "DUPLICATE_PRODUCT_GROUP",
  PRODUCT_GROUP_IN_USE: "PRODUCT_GROUP_IN_USE",

  // Inventory: products
  PRODUCT_NOT_FOUND: "PRODUCT_NOT_FOUND",
  DUPLICATE_SKU: "DUPLICATE_SKU",
  PRODUCT_IN_USE: "PRODUCT_IN_USE",

  // Inventory: product units
  UNIT_NOT_FOUND: "UNIT_NOT_FOUND",
  DUPLICATE_UNIT: "DUPLICATE_UNIT",
  UNIT_INACTIVE: "UNIT_INACTIVE",
  BASE_UNIT_REQUIRED: "BASE_UNIT_REQUIRED",
  BASE_UNIT_EXISTS: "BASE_UNIT_EXISTS",
  BASE_UNIT_FORBIDDEN: "BASE_UNIT_FORBIDDEN",
  INVALID_CONVERSION_FACTOR: "INVALID_CONVERSION_FACTOR",
  UNIT_PRODUCT_MISMATCH: "UNIT_PRODUCT_MISMATCH",

  // Inventory: transfers
  DUPLICATE_TRANSFER_ITEM: "DUPLICATE_TRANSFER_ITEM",
  TRANSFER_NOT_EDITABLE: "TRANSFER_NOT_EDITABLE",

  // Inventory: locations
  LOCATION_NOT_FOUND: "LOCATION_NOT_FOUND",
  DUPLICATE_LOCATION: "DUPLICATE_LOCATION",
  LOCATION_IN_USE: "LOCATION_IN_USE",
  INACTIVE_LOCATION: "INACTIVE_LOCATION",

  // Inventory: batches
  BATCH_NOT_FOUND: "BATCH_NOT_FOUND",
  DUPLICATE_BATCH: "DUPLICATE_BATCH",
  BATCH_PRODUCT_MISMATCH: "BATCH_PRODUCT_MISMATCH",
  INVALID_EXPIRY_DATE: "INVALID_EXPIRY_DATE",
  EXPIRED_BATCH: "EXPIRED_BATCH",
  BATCH_IN_USE: "BATCH_IN_USE",

  // Inventory: stock movements
  INSUFFICIENT_STOCK: "INSUFFICIENT_STOCK",
  INVALID_STOCK_QUANTITY: "INVALID_STOCK_QUANTITY",
  INVALID_UNIT: "INVALID_UNIT",

  // Purchasing: suppliers
  SUPPLIER_NOT_FOUND: "SUPPLIER_NOT_FOUND",
  DUPLICATE_SUPPLIER: "DUPLICATE_SUPPLIER",
  SUPPLIER_IN_USE: "SUPPLIER_IN_USE",
  INACTIVE_SUPPLIER: "INACTIVE_SUPPLIER",

  // Purchasing: purchase requirements
  REQUIREMENT_NOT_FOUND: "REQUIREMENT_NOT_FOUND",
  REQUIREMENT_LINE_NOT_FOUND: "REQUIREMENT_LINE_NOT_FOUND",
  REQUIREMENT_CLOSED: "REQUIREMENT_CLOSED",
  REQUIREMENT_LINE_HAS_PO: "REQUIREMENT_LINE_HAS_PO",
  DUPLICATE_PRODUCT_IN_REQUIREMENT: "DUPLICATE_PRODUCT_IN_REQUIREMENT",
  REQUIREMENT_LINE_MISMATCH_SUPPLIER: "REQUIREMENT_LINE_MISMATCH_SUPPLIER",

  // Purchasing: purchase orders
  PURCHASE_ORDER_NOT_FOUND: "PURCHASE_ORDER_NOT_FOUND",
  DUPLICATE_PO_NUMBER: "DUPLICATE_PO_NUMBER",
  PURCHASE_ORDER_ITEM_NOT_FOUND: "PURCHASE_ORDER_ITEM_NOT_FOUND",
  PO_STATUS_TRANSITION_INVALID: "PO_STATUS_TRANSITION_INVALID",
  PO_CANNOT_CANCEL: "PO_CANNOT_CANCEL",
  PO_REQUIREMENT_LINE_SUPPLIER_MISMATCH: "PO_REQUIREMENT_LINE_SUPPLIER_MISMATCH",

  // Purchasing: goods receipts
  GOODS_RECEIPT_NOT_FOUND: "GOODS_RECEIPT_NOT_FOUND",
  GOODS_RECEIPT_ITEM_NOT_FOUND: "GOODS_RECEIPT_ITEM_NOT_FOUND",
  GOODS_RECEIPT_ALREADY_CONFIRMED: "GOODS_RECEIPT_ALREADY_CONFIRMED",
  GOODS_RECEIPT_CANNOT_CONFIRM: "GOODS_RECEIPT_CANNOT_CONFIRM",
  GOODS_RECEIPT_DISCREPANCY_UNRESOLVED: "GOODS_RECEIPT_DISCREPANCY_UNRESOLVED",
  GOODS_RECEIPT_BATCH_REQUIRED: "GOODS_RECEIPT_BATCH_REQUIRED",
  GOODS_RECEIPT_EXPIRY_REQUIRED: "GOODS_RECEIPT_EXPIRY_REQUIRED",
  GR_ITEM_QUANTITY_MISMATCH: "GR_ITEM_QUANTITY_MISMATCH",

  // Purchasing: supplier invoices
  SUPPLIER_INVOICE_NOT_FOUND: "SUPPLIER_INVOICE_NOT_FOUND",
  DUPLICATE_INVOICE_NUMBER: "DUPLICATE_INVOICE_NUMBER",
  SUPPLIER_INVOICE_PAYMENT_EXCEEDS_BALANCE: "SUPPLIER_INVOICE_PAYMENT_EXCEEDS_BALANCE",

  // Purchasing: purchase returns
  PURCHASE_RETURN_NOT_FOUND: "PURCHASE_RETURN_NOT_FOUND",
  DUPLICATE_RETURN_NUMBER: "DUPLICATE_RETURN_NUMBER",
  PURCHASE_RETURN_INSUFFICIENT_STOCK: "PURCHASE_RETURN_INSUFFICIENT_STOCK",
  // POS: sales
  PRODUCT_INACTIVE: "PRODUCT_INACTIVE",
  UNIT_NO_SELL_PRICE: "UNIT_NO_SELL_PRICE",
  INSUFFICIENT_PAYMENT: "INSUFFICIENT_PAYMENT",
  SALE_NOT_FOUND: "SALE_NOT_FOUND",
  SALE_NOT_CANCELLABLE: "SALE_NOT_CANCELLABLE",
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
