export const ErrorCode = {
  BAD_REQUEST: "BAD_REQUEST",
  UNAUTHENTICATED: "UNAUTHENTICATED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  RATE_LIMITED: "RATE_LIMITED",
  DATABASE_ERROR: "DATABASE_ERROR",
  INTERNAL_ERROR: "INTERNAL_ERROR",

  // Inventory: product groups
  PRODUCT_GROUP_NOT_FOUND: "PRODUCT_GROUP_NOT_FOUND",
  DUPLICATE_PRODUCT_GROUP: "DUPLICATE_PRODUCT_GROUP",
  PRODUCT_GROUP_IN_USE: "PRODUCT_GROUP_IN_USE",

  // Inventory: products
  PRODUCT_NOT_FOUND: "PRODUCT_NOT_FOUND",
  DUPLICATE_SKU: "DUPLICATE_SKU",
  PRODUCT_IN_USE: "PRODUCT_IN_USE",

  // Inventory: product units
  UNIT_NOT_FOUND: "UNIT_NOT_FOUND",
  DUPLICATE_UNIT: "DUPLICATE_UNIT",
  BASE_UNIT_EXISTS: "BASE_UNIT_EXISTS",
  BASE_UNIT_FORBIDDEN: "BASE_UNIT_FORBIDDEN",
  INVALID_CONVERSION_FACTOR: "INVALID_CONVERSION_FACTOR",
  UNIT_PRODUCT_MISMATCH: "UNIT_PRODUCT_MISMATCH",

  // Inventory: locations
  LOCATION_NOT_FOUND: "LOCATION_NOT_FOUND",
  DUPLICATE_LOCATION: "DUPLICATE_LOCATION",
  LOCATION_IN_USE: "LOCATION_IN_USE",
  INACTIVE_LOCATION: "INACTIVE_LOCATION",

  // Inventory: batches
  BATCH_NOT_FOUND: "BATCH_NOT_FOUND",
  DUPLICATE_BATCH: "DUPLICATE_BATCH",
  BATCH_PRODUCT_MISMATCH: "BATCH_PRODUCT_MISMATCH",
  INVALID_EXPIRY_DATE: "INVALID_EXPIRY_DATE",
  EXPIRED_BATCH: "EXPIRED_BATCH",
  BATCH_IN_USE: "BATCH_IN_USE",

  // Inventory: stock movements
  INSUFFICIENT_STOCK: "INSUFFICIENT_STOCK",
  INVALID_STOCK_QUANTITY: "INVALID_STOCK_QUANTITY",
  INVALID_UNIT: "INVALID_UNIT",
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
